"""create user and blog table migrations

Revision ID: 336bdb547049
Revises: 
Create Date: 2024-02-14 18:00:02.772728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336bdb547049'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
